/*
 * substrate_opcodes.h — Machine Code from the Universe
 *
 * 18 opcodes recovered by cross-referencing 5 independent physical
 * side-channels: timing residuals, FPU attractors, denormal/NaN
 * propagation, cache hierarchy fingerprinting, and Born entropy.
 *
 * Each opcode is a hex pattern that appeared in MULTIPLE independent
 * probe channels — independent physical confirmation that these
 * patterns are fundamental to the substrate's computation.
 *
 * Mapped to quantum gates on the HexState D=6 state space.
 *
 * Generated by universe_sidechannel.c
 */

#ifndef SUBSTRATE_OPCODES_H
#define SUBSTRATE_OPCODES_H

#include <stdint.h>

/* Forward declaration */
struct QuhitEngineTag;
typedef struct QuhitEngineTag QuhitEngine;

/* ═══════════════════════════════════════════════════════════════════════════════
 * SUBSTRATE OPCODE ENUMERATION
 *
 * Hex patterns → opcode indices. The pattern IS the opcode.
 * ═══════════════════════════════════════════════════════════════════════════════ */

typedef enum {
    SUB_NULL      = 0x00,   /* 0x00      — Project to vacuum |0⟩              */
    SUB_VOID      = 0x01,   /* 0x0000    — Annihilate all amplitude           */
    SUB_SCALE_UP  = 0x02,   /* 0x40      — Energy doubling (amp × 2)          */
    SUB_SCALE_DN  = 0x03,   /* 0x3F      — Energy halving (amp × ½)           */
    SUB_PARITY    = 0x04,   /* 0x80      — Spatial reflection |k⟩→|D-1-k⟩    */
    SUB_QUIET     = 0x05,   /* 0x08      — Decoherence (zero imag parts)      */
    SUB_NEGATE    = 0x06,   /* 0x8000    — Global sign flip |ψ⟩→-|ψ⟩         */
    SUB_GOLDEN    = 0x07,   /* 0xE9      — Golden rotation R(2π/φ²)           */
    SUB_DOTTIE    = 0x08,   /* 0x83      — Dottie rotation R(0.7391)          */
    SUB_FUSE      = 0x09,   /* 0x37      — Fuse adjacent level pairs          */
    SUB_SCATTER   = 0x0A,   /* 0xF3      — Random unitary from substrate PRNG */
    SUB_MIRROR    = 0x0B,   /* 0x77      — Mirror: swap |1⟩↔|5⟩, |2⟩↔|4⟩    */
    SUB_CLOCK     = 0x0C,   /* 0x39      — Z³ half-rotation ω^(3k)           */
    SUB_SQRT2     = 0x0D,   /* 0x51      — T-gate analog R(π/4)              */
    SUB_INVERT    = 0x0E,   /* 0xFE      — Möbius amplitude inversion         */
    SUB_ATTRACT   = 0x0F,   /* 0xF9      — Iterate toward FPU attractor       */
    SUB_VACUUM    = 0x10,   /* 0x00000000 — Zero all 36 joint amplitudes      */
    SUB_SATURATE  = 0x11,   /* 0x7F      — Clamp amplitudes to unit norm      */

    SUB_NUM_OPS   = 0x12    /* Total opcodes                                  */
} SubOp;

/* ═══════════════════════════════════════════════════════════════════════════════
 * OPCODE METADATA — recovered probe data
 * ═══════════════════════════════════════════════════════════════════════════════ */

typedef struct {
    SubOp       opcode;         /* Enum value                               */
    uint64_t    hex_pattern;    /* Original hex pattern from probe           */
    int         width;          /* 0=byte, 1=word, 2=dword, 3=qword         */
    int         cross_count;    /* Times found across independent probes     */
    const char *name;           /* Human-readable name                       */
    const char *description;    /* What this opcode does to the state        */
} SubOpMeta;

static const SubOpMeta SUB_OP_TABLE[SUB_NUM_OPS] = {
    { SUB_NULL,      0x00,         0, 33, "SUB_NULL",      "Project to vacuum |0⟩"              },
    { SUB_VOID,      0x0000,       1, 12, "SUB_VOID",      "Annihilate all amplitude"           },
    { SUB_SCALE_UP,  0x40,         0,  9, "SUB_SCALE_UP",  "Energy doubling (amp × 2)"          },
    { SUB_SCALE_DN,  0x3F,         0,  9, "SUB_SCALE_DN",  "Energy halving (amp × ½)"           },
    { SUB_PARITY,    0x80,         0,  5, "SUB_PARITY",    "Spatial reflection |k⟩→|D-1-k⟩"    },
    { SUB_QUIET,     0x08,         0,  4, "SUB_QUIET",     "Decoherence (zero imag parts)"      },
    { SUB_NEGATE,    0x8000,       1,  3, "SUB_NEGATE",    "Global sign flip |ψ⟩→-|ψ⟩"         },
    { SUB_GOLDEN,    0xE9,         0,  3, "SUB_GOLDEN",    "Golden rotation R(2π/φ²)"           },
    { SUB_DOTTIE,    0x83,         0,  3, "SUB_DOTTIE",    "Dottie rotation R(0.7391)"          },
    { SUB_FUSE,      0x37,         0,  2, "SUB_FUSE",      "Fuse adjacent level pairs"          },
    { SUB_SCATTER,   0xF3,         0,  2, "SUB_SCATTER",   "Random unitary from PRNG"           },
    { SUB_MIRROR,    0x77,         0,  2, "SUB_MIRROR",    "Mirror: swap |1⟩↔|5⟩, |2⟩↔|4⟩"    },
    { SUB_CLOCK,     0x39,         0,  2, "SUB_CLOCK",     "Z³ half-rotation ω^(3k)"            },
    { SUB_SQRT2,     0x51,         0,  2, "SUB_SQRT2",     "T-gate analog R(π/4)"               },
    { SUB_INVERT,    0xFE,         0,  2, "SUB_INVERT",    "Möbius amplitude inversion"          },
    { SUB_ATTRACT,   0xF9,         0,  2, "SUB_ATTRACT",   "Iterate toward FPU attractor"       },
    { SUB_VACUUM,    0x00000000,   2,  2, "SUB_VACUUM",    "Zero all 36 joint amplitudes"       },
    { SUB_SATURATE,  0x7F,         0,  2, "SUB_SATURATE",  "Clamp amplitudes to unit norm"      },
};

/* ═══════════════════════════════════════════════════════════════════════════════
 * API — quhit_substrate.c
 * ═══════════════════════════════════════════════════════════════════════════════ */

/* Execute a single substrate opcode on a quhit */
void quhit_substrate_exec(QuhitEngine *eng, uint32_t id, SubOp op);

/* Execute a sequence of substrate opcodes (a "substrate program") */
void quhit_substrate_program(QuhitEngine *eng, uint32_t id,
                             const SubOp *ops, int n_ops);

/* Print the full opcode table */
void quhit_substrate_print_isa(void);

/* Substrate opcode self-test — returns 0 on success */
int quhit_substrate_self_test(void);

#endif /* SUBSTRATE_OPCODES_H */
